// Auto-generated from Master Intake Database.xlsx by
// C:/Users/maxra/Documents/Wildlife Rescue/Data/Master Data/export_intake_data.py
// DO NOT EDIT BY HAND — re-run the script to refresh.
//
// Coverage: 39,681 cases across 23 years (2010 – 2026 partial).
// IUCN status from public IUCN Red List data, hand-filled for top species.

export type SpeciesRow = {
  name: string;
  cases: number;
  iucn: "CR" | "EN" | "VU" | "NT" | "LC" | "DD" | null;
};
export type ConditionRow = { name: string; cases: number };
export type AgeRow = { name: string; cases: number };
export type PartnerRow = { name: string; cases: number };
export type YearRow = { year: number; cases: number };

export const INTAKE_TOTAL = 39681;
export const INTAKE_CASES_WITH_CONDITION = 7230;
export const INTAKE_CASES_WITH_AGE = 2200;

export const SPECIES_BREAKDOWN: SpeciesRow[] = [
  { name: "Black Kite", cases: 32510, iucn: "LC" },
  { name: "Blue Rock Pigeon", cases: 1344, iucn: "LC" },
  { name: "Barn Owl", cases: 1078, iucn: "LC" },
  { name: "Black Eared Kite", cases: 750, iucn: "LC" },
  { name: "Shikra", cases: 461, iucn: "LC" },
  { name: "Cattle Egret", cases: 418, iucn: "LC" },
  { name: "Common Crow", cases: 342, iucn: "LC" },
  { name: "Spotted Owlet", cases: 158, iucn: "LC" },
  { name: "Indian Grey Hornbill", cases: 126, iucn: "LC" },
  { name: "Crested Serpent Eagle", cases: 125, iucn: "LC" },
  { name: "White-Throated Kingfisher", cases: 72, iucn: "LC" },
  { name: "Pigeon", cases: 67, iucn: null },
  { name: "Red-Wattled Lapwing", cases: 67, iucn: "LC" },
  { name: "Egyptian Vulture", cases: 66, iucn: "EN" },
  { name: "Red-Naped Ibis", cases: 66, iucn: "LC" },
  { name: "Yellow Footed Green Pigeon", cases: 57, iucn: "LC" },
  { name: "Black Headed Gull", cases: 57, iucn: "LC" },
  { name: "Asian Koel", cases: 55, iucn: "LC" },
  { name: "Brown Headed Barbet", cases: 51, iucn: "LC" },
  { name: "Five-Striped Palm Squirrel", cases: 48, iucn: "LC" },
  { name: "Indian Scops Owl", cases: 48, iucn: "LC" },
  { name: "Black Headed Ibis", cases: 47, iucn: "NT" },
  { name: "Pond Heron", cases: 46, iucn: "LC" },
  { name: "Rose-Ringed Parakeet", cases: 44, iucn: "LC" },
  { name: "Common Myna", cases: 38, iucn: "LC" },
  { name: "Painted Stork", cases: 34, iucn: "NT" },
  { name: "Eurasian Thick-Knee", cases: 29, iucn: "LC" },
  { name: "White-Breasted Waterhen", cases: 27, iucn: "LC" },
  { name: "Night Heron", cases: 26, iucn: "LC" },
  { name: "Eurasian Collared Dove", cases: 21, iucn: "LC" },
  { name: "Common Coot", cases: 20, iucn: "LC" },
  { name: "Common Moorhen", cases: 19, iucn: "LC" },
  { name: "Alexandrine Parakeet", cases: 18, iucn: "NT" },
  { name: "Oriental Honey Buzzard", cases: 16, iucn: "LC" },
  { name: "Indian Cormorant", cases: 16, iucn: "LC" },
  { name: "Indian Treepie", cases: 15, iucn: "LC" },
  { name: "Kitten", cases: 12, iucn: null },
  { name: "Red Sand Boa", cases: 10, iucn: "NT" },
  { name: "Fruit Bat", cases: 10, iucn: "LC" },
  { name: "Grey Heron", cases: 10, iucn: "LC" },
  { name: "House Swift", cases: 10, iucn: "LC" },
  { name: "Japanese Quail", cases: 8, iucn: "NT" },
  { name: "Indian Nightjar", cases: 8, iucn: "LC" },
  { name: "Black Rumped Flameback", cases: 8, iucn: "LC" },
  { name: "Indian Peafowl", cases: 7, iucn: "LC" },
  { name: "Short-Toed Snake Eagle", cases: 7, iucn: "LC" },
  { name: "Cat", cases: 7, iucn: null },
  { name: "Wolf Snake", cases: 7, iucn: "LC" },
  { name: "Water Cock", cases: 7, iucn: "LC" },
  { name: "Booted Eagle", cases: 7, iucn: "LC" },
  { name: "Checkered Keel Back", cases: 6, iucn: "LC" },
  { name: "Rock Eagle Owl", cases: 6, iucn: "LC" },
  { name: "Asian Pied Starling", cases: 6, iucn: "LC" },
  { name: "Greater Coucal", cases: 6, iucn: "LC" },
  { name: "Pallid Scops Owl", cases: 6, iucn: "LC" },
  { name: "Indian Cobra", cases: 6, iucn: "LC" },
  { name: "Lesser Coucal", cases: 6, iucn: "LC" },
  { name: "Great Egret", cases: 6, iucn: "LC" },
  { name: "Peregrine Falcon", cases: 6, iucn: "LC" },
  { name: "White Eyed Buzzard", cases: 5, iucn: "LC" },
  { name: "Black-Winged Kite", cases: 5, iucn: "LC" },
  { name: "Coppersmith Barbet", cases: 5, iucn: "LC" },
  { name: "Jungle Babbler", cases: 5, iucn: "LC" },
  { name: "Brown Hawk Owl", cases: 5, iucn: "LC" },
  { name: "House Sparrow", cases: 4, iucn: "LC" },
  { name: "Common Buzzard", cases: 4, iucn: "LC" },
  { name: "Black-Winged Stilt", cases: 4, iucn: "LC" },
  { name: "Rabbit", cases: 3, iucn: "LC" },
  { name: "Duck", cases: 3, iucn: "LC" },
  { name: "Unknown Bird", cases: 3, iucn: null },
  { name: "Soft Shelled Turtle", cases: 3, iucn: "VU" },
  { name: "Steppe Eagle", cases: 2, iucn: "EN" },
  { name: "Mongoose", cases: 2, iucn: "LC" },
  { name: "Indian Lorikeet", cases: 2, iucn: "LC" },
  { name: "Bulbul", cases: 2, iucn: "LC" },
  { name: "Bat", cases: 2, iucn: "LC" },
  { name: "Magpie", cases: 2, iucn: "LC" },
  { name: "Rat Snake", cases: 2, iucn: "LC" },
  { name: "Common Sand Boa", cases: 2, iucn: "LC" },
  { name: "Brown Fish Owl", cases: 2, iucn: "LC" },
  { name: "Little Cormorant", cases: 2, iucn: "LC" },
  { name: "Common Hoopoe", cases: 2, iucn: "LC" },
  { name: "Bar Headed Goose", cases: 2, iucn: "LC" },
  { name: "Spotted Black Terrapin", cases: 2, iucn: "LC" },
  { name: "Brown Crake", cases: 2, iucn: "LC" },
  { name: "Eurasian Marsh Harrier", cases: 2, iucn: "LC" },
  { name: "Plum Headed Parakeet", cases: 2, iucn: "LC" },
  { name: "Purple Swamphen", cases: 2, iucn: "LC" },
  { name: "Jungle Owlet", cases: 2, iucn: "LC" },
  { name: "Indian Pitta", cases: 2, iucn: "LC" },
  { name: "Eurasian Hobby", cases: 2, iucn: "LC" },
  { name: "Monitor Lizard", cases: 2, iucn: "LC" },
  { name: "Bulldog Faced Bat", cases: 2, iucn: null },
  { name: "Indian Spot Billed Duck", cases: 2, iucn: "LC" },
  { name: "Pied Harrier", cases: 1, iucn: "VU" },
  { name: "Budgerigar", cases: 1, iucn: null },
  { name: "Common Kestrel", cases: 1, iucn: "LC" },
  { name: "Hen Chick", cases: 1, iucn: null },
  { name: "Guinea Fowl", cases: 1, iucn: "LC" },
  { name: "Zebra Finch", cases: 1, iucn: null },
  { name: "Munia", cases: 1, iucn: null },
  { name: "Woodpecker", cases: 1, iucn: "LC" },
  { name: "Eurasian Griffon", cases: 1, iucn: "LC" },
  { name: "Northern Shoveler", cases: 1, iucn: "LC" },
  { name: "Yellow Crowned Woodpecker", cases: 1, iucn: "LC" },
  { name: "Cuckoo", cases: 1, iucn: "LC" },
  { name: "Besra", cases: 1, iucn: "LC" },
  { name: "Ruff", cases: 1, iucn: "LC" },
  { name: "Great White Pelican", cases: 1, iucn: "LC" },
  { name: "Glossy Ibis", cases: 1, iucn: "LC" },
  { name: "Orange Headed Thrush", cases: 1, iucn: "LC" },
  { name: "Common Kukri", cases: 1, iucn: "LC" },
  { name: "Flamingo", cases: 1, iucn: "LC" },
  { name: "Great Crested Grebe", cases: 1, iucn: "LC" },
  { name: "Grey Francolin", cases: 1, iucn: "LC" },
  { name: "Indian Stone Curlew", cases: 1, iucn: "LC" },
  { name: "Jungle Nightjar", cases: 1, iucn: "LC" },
  { name: "Common Hawk Cuckoo", cases: 1, iucn: "LC" },
  { name: "Purple Heron", cases: 1, iucn: "LC" },
  { name: "Indian Tent Turtle", cases: 1, iucn: "LC" },
  { name: "Barn Swallow", cases: 1, iucn: "LC" },
  { name: "Three Striped Roofed Terrapin", cases: 1, iucn: "NT" },
  { name: "Long Eared Owl", cases: 1, iucn: "LC" },
  { name: "Long Legged Buzzard", cases: 1, iucn: "LC" },
  { name: "Savannah Nightjar", cases: 1, iucn: "LC" },
  { name: "Buffstriped Keelback", cases: 1, iucn: "LC" },
  { name: "Indian Roller", cases: 1, iucn: "LC" },
  { name: "Oriental Scops Owl", cases: 1, iucn: "LC" },
  { name: "Woolly Necked Stork", cases: 1, iucn: "NT" },
  { name: "Common Redshank", cases: 1, iucn: "LC" },
  { name: "Indian Darter", cases: 1, iucn: "NT" },
  { name: "Black Bittern", cases: 1, iucn: "LC" },
  { name: "Laggar Falcon", cases: 1, iucn: "NT" },
  { name: "Greylag Goose", cases: 1, iucn: "LC" },
  { name: "Little Grebe", cases: 1, iucn: "LC" },
  { name: "Eastern Imperial Eagle", cases: 1, iucn: "VU" },
  { name: "Great Cormorant", cases: 1, iucn: "LC" },
  { name: "Black Stork", cases: 1, iucn: "LC" },
];

export const CONDITION_BREAKDOWN: ConditionRow[] = [
  { name: "Manja Injuries & Cut Wounds", cases: 2824 },
  { name: "Fractures", cases: 1178 },
  { name: "Septicemia & Infections", cases: 285 },
  { name: "Amputation", cases: 212 },
  { name: "Orphans, Chicks & Juveniles", cases: 1337 },
  { name: "Paralysis & Neurological", cases: 188 },
  { name: "Head & Eye Injuries", cases: 59 },
  { name: "Burns", cases: 1 },
  { name: "Edema & Swelling", cases: 52 },
  { name: "Abrasions & Stiffness", cases: 44 },
  { name: "Tumours & Growths", cases: 22 },
  { name: "Poisoning", cases: 13 },
  { name: "Glue & Trap Entanglement", cases: 25 },
  { name: "Animal Attack", cases: 17 },
  { name: "Metabolic & Nutritional", cases: 269 },
  { name: "Feather Damage", cases: 136 },
  { name: "External Examination Normal", cases: 471 },
  { name: "Other / Various", cases: 97 },
];

export const AGE_BREAKDOWN: AgeRow[] = [
  { name: "Adult (implied)", cases: 37481 },
  { name: "Juvenile", cases: 516 },
  { name: "Fledgling", cases: 610 },
  { name: "Nestling", cases: 890 },
  { name: "Hatchling", cases: 184 },
];

export const PARTNER_BREAKDOWN: PartnerRow[] = [
  { name: "Charity Birds Hospital", cases: 20099 },
  { name: "S.V.S.J. Sewa Trust", cases: 4643 },
  { name: "Sanjay Gandhi Animal Care Center", cases: 3781 },
  { name: "Prem Bhawan", cases: 2673 },
  { name: "Unknown", cases: 608 },
  { name: "P.K. Wildlife & Birds Rescue Team", cases: 383 },
  { name: "Wildlife SOS", cases: 167 },
  { name: "Deputy Conservator Of Forest", cases: 155 },
  { name: "Bail A Tail", cases: 122 },
  { name: "Angel Eyes", cases: 119 },
  { name: "Vidya Sagar Jeevdaya Parivaar Trust", cases: 119 },
  { name: "Friendicoes", cases: 104 },
  { name: "Fauna Foundation", cases: 100 },
  { name: "Sagar Dharmarth Bird Care Trust", cases: 94 },
  { name: "Abhinav Garg", cases: 76 },
  { name: "Office Of Deputy Conservator Of Forest", cases: 74 },
  { name: "Bird Hospital Shahdara", cases: 65 },
  { name: "SVNS Jain Seva Trust", cases: 54 },
  { name: "Not Available in Records", cases: 48 },
  { name: "Sagar Dharmarth Birds Care Trust", cases: 47 },
  { name: "Angle Eyes", cases: 46 },
  { name: "Friendicos", cases: 45 },
  { name: "Chehek Charitable Trust", cases: 32 },
  { name: "Rajiv Jain", cases: 29 },
  { name: "Bhagwan Mahavir Swami Bird Home & Hospital", cases: 26 },
  { name: "Prem Bhavan", cases: 24 },
  { name: "Nadeem Shehzad", cases: 18 },
  { name: "PFA Faridabad", cases: 16 },
  { name: "Memuna", cases: 15 },
  { name: "Memoona Khatoon", cases: 15 },
  { name: "S.D.B. Care Trust", cases: 15 },
  { name: "Unknown Kids", cases: 14 },
  { name: "Fishan", cases: 14 },
  { name: "Saleem", cases: 13 },
  { name: "Delhi Jal Board", cases: 13 },
  { name: "Rajeev Jain", cases: 10 },
  { name: "Asad Khan", cases: 10 },
  { name: "Indian Air Force Head Quarters", cases: 10 },
  { name: "Unkmown", cases: 10 },
  { name: "Farmaan", cases: 9 },
  { name: "Gaurav", cases: 9 },
  { name: "Delhi Forest Department", cases: 9 },
  { name: "Chehek Charity Trust", cases: 9 },
  { name: "Memoona", cases: 8 },
  { name: "Shahid", cases: 8 },
  { name: "Baljeet Kaur", cases: 8 },
  { name: "Farman", cases: 8 },
  { name: "PCR Call", cases: 7 },
  { name: "Lalit", cases: 7 },
  { name: "Nadeem", cases: 6 },
  { name: "Om Veer", cases: 6 },
  { name: "Mr.Chote lal", cases: 6 },
  { name: "Delhi Fire Service", cases: 6 },
  { name: "Mohammad Farman", cases: 6 },
  { name: "Suresh Kumar", cases: 6 },
  { name: "Fateh Singh Gaurav", cases: 6 },
  { name: "Mohammad Saud", cases: 6 },
  { name: "SDB Care Trust", cases: 6 },
  { name: "P.K. Wildlife Rescue", cases: 6 },
  { name: "M/S. Godhan Sewa Samiti", cases: 6 },
  { name: "Bhagwan Mahavir Swami Birds Home & Hospital", cases: 6 },
  { name: "Anirudh Bhardwaj", cases: 5 },
  { name: "Uma Menon", cases: 5 },
  { name: "WSOS", cases: 5 },
  { name: "Lady Reading Health School", cases: 5 },
  { name: "Paras Sewa Sansthan", cases: 5 },
  { name: "New Delhi Nature Society", cases: 5 },
  { name: "Bhargavi Pathak", cases: 5 },
  { name: "Bail A Trail", cases: 5 },
  { name: "Manta", cases: 4 },
  { name: "Ravi Dubey", cases: 4 },
  { name: "Abhishek", cases: 4 },
  { name: "Fire Station", cases: 4 },
  { name: "Nimai Chadha", cases: 4 },
  { name: "Kishan Kumar", cases: 4 },
  { name: "Tanveer", cases: 4 },
  { name: "Yogesh Goyal", cases: 4 },
  { name: "Unkown", cases: 4 },
  { name: "SDBCT", cases: 4 },
  { name: "Bhagwan Mahaveer Bird Home & Hospital", cases: 4 },
  { name: "Salik", cases: 3 },
  { name: "Abdul Naim", cases: 3 },
  { name: "Manta Sidhu", cases: 3 },
  { name: "Mrs.Shabnam", cases: 3 },
  { name: "Prime Minister House", cases: 3 },
  { name: "Abhinav Srihan", cases: 3 },
  { name: "Suhail", cases: 3 },
  { name: "Aslam", cases: 3 },
  { name: "Vipin Kumar", cases: 3 },
  { name: "Sunil Kumar", cases: 3 },
  { name: "Mukesh", cases: 3 },
  { name: "R.D. Mishra", cases: 3 },
  { name: "Police Control Room", cases: 3 },
  { name: "Rafat", cases: 3 },
  { name: "Black Kite", cases: 3 },
  { name: "mohammad Shahid", cases: 3 },
  { name: "Raj Kumar", cases: 3 },
  { name: "Muslim", cases: 3 },
  { name: "PS Parliment Street", cases: 3 },
  { name: "PFA", cases: 3 },
  { name: "Baster Pumping Station", cases: 3 },
  { name: "H.C Rishi Raj", cases: 3 },
  { name: "Mr.Vikas Kumar", cases: 2 },
  { name: "Pooran lal sharma", cases: 2 },
  { name: "Sandeep", cases: 2 },
  { name: "Fardeen", cases: 2 },
  { name: "Yusuf", cases: 2 },
  { name: "Mr.Masroor Hasan", cases: 2 },
  { name: "Mr.Sonu Kumar", cases: 2 },
  { name: "Naeem", cases: 2 },
  { name: "Mr.Kashyap", cases: 2 },
  { name: "Mr.Jaswant Singh", cases: 2 },
  { name: "Yusuf Ali", cases: 2 },
  { name: "Delhi Jal Board Ramlila Maidan", cases: 2 },
  { name: "Rahul Singh", cases: 2 },
  { name: "Cawar bagli", cases: 2 },
  { name: "Mohd. Yusuf ali", cases: 2 },
  { name: "Mohd. Irfan", cases: 2 },
  { name: "Manoj Kumar", cases: 2 },
  { name: "S.I. Yogesh Kumar", cases: 2 },
  { name: "Mohd Naeem", cases: 2 },
  { name: "Ajay Kumar", cases: 2 },
  { name: "Aman", cases: 2 },
  { name: "Mohd Shahid", cases: 2 },
  { name: "Sufiyaan", cases: 2 },
  { name: "Mohammad Izhan", cases: 2 },
  { name: "Mohd Salman", cases: 2 },
  { name: "Fire Officer Dharam Pal", cases: 2 },
  { name: "H. C. Roop Kishor", cases: 2 },
  { name: "Utkarsh Sonker", cases: 2 },
  { name: "Suresh", cases: 2 },
  { name: "JBH Shahadara", cases: 2 },
  { name: "Krishan Kumar", cases: 2 },
  { name: "Shabnam Bano", cases: 2 },
  { name: "Mohammad Irfan", cases: 2 },
  { name: "Dharam Pal", cases: 2 },
  { name: "Jagruti", cases: 2 },
  { name: "LNJP Hospital", cases: 2 },
  { name: "Anglo Arabic School", cases: 2 },
  { name: "Akash", cases: 2 },
  { name: "Govt. School", cases: 2 },
  { name: "H.C. Rishi Pal Rana", cases: 2 },
  { name: "Raj Kumar Sharma", cases: 2 },
  { name: "Saif", cases: 2 },
  { name: "Shakil Ahmad", cases: 2 },
  { name: "Memoona Katoon", cases: 2 },
  { name: "Lucky", cases: 2 },
  { name: "Embassy Of Turkey", cases: 2 },
  { name: "Zameer", cases: 2 },
  { name: "Kishan", cases: 2 },
  { name: "Abdur Rehman", cases: 2 },
  { name: "Himanshu", cases: 2 },
  { name: "Raju", cases: 2 },
  { name: "Manoj Gupta", cases: 2 },
  { name: "Jeet Lal", cases: 2 },
  { name: "Pradeep", cases: 2 },
  { name: "Rizwan", cases: 2 },
  { name: "Sukh Swaroop Birds Care Foundation", cases: 2 },
  { name: "Rishi Kapoor", cases: 2 },
  { name: "Rafeeq", cases: 2 },
  { name: "Memuna Khatoon", cases: 2 },
  { name: "Anirudh", cases: 2 },
  { name: "Willson", cases: 2 },
  { name: "Pandit Ji", cases: 2 },
  { name: "S.I. Mr. Brijesh", cases: 2 },
  { name: "Delhi Jal Broard", cases: 2 },
  { name: "DMRC", cases: 2 },
  { name: "Shri Sanstha", cases: 2 },
  { name: "Mohit Somany", cases: 2 },
  { name: "Sagar Dharma Bird Care Trust", cases: 2 },
  { name: "Ally Medicos", cases: 2 },
  { name: "Ma. Tabassum", cases: 2 },
  { name: "M/s. Bhagwan Mahavir Swami Pakshi Awaas &Chikisalya", cases: 2 },
  { name: "Jeev Upkar Trust", cases: 2 },
  { name: "Live Dogs States", cases: 2 },
  { name: "P.C. Jain Ji", cases: 2 },
  { name: "Mohammad Aslam", cases: 1 },
  { name: "M. Shahid", cases: 1 },
  { name: "M. saleem", cases: 1 },
  { name: "M. Naim", cases: 1 },
  { name: "Oais", cases: 1 },
  { name: "Shehzad", cases: 1 },
  { name: "Gourav Gupta", cases: 1 },
  { name: "Parashar", cases: 1 },
  { name: "Garbage Dump Worker", cases: 1 },
  { name: "Nand Kishore", cases: 1 },
  { name: "M. Saud", cases: 1 },
  { name: "Sandeep Suri", cases: 1 },
  { name: "Nawab", cases: 1 },
  { name: "Mohammad Rashid", cases: 1 },
  { name: "Naved Alam", cases: 1 },
  { name: "Manoj Tyagi", cases: 1 },
  { name: "Akshay mehta", cases: 1 },
  { name: "Vigor Sharma", cases: 1 },
  { name: "Shareef", cases: 1 },
  { name: "Mohammad Shariq", cases: 1 },
  { name: "M. Izhan", cases: 1 },
  { name: "Zia ul Islam", cases: 1 },
  { name: "M. Salman", cases: 1 },
  { name: "Piyush Bajaj", cases: 1 },
  { name: "Mauta Sidhu", cases: 1 },
  { name: "M. Naumaan", cases: 1 },
  { name: "M. Salik ur Rehman", cases: 1 },
  { name: "Church Father", cases: 1 },
  { name: "Mohammed Shareef", cases: 1 },
  { name: "Punam Kashyap", cases: 1 },
  { name: "Swati", cases: 1 },
  { name: "Rishi Bal Chowdhri", cases: 1 },
  { name: "Ashu", cases: 1 },
  { name: "Qudsia", cases: 1 },
  { name: "Vijay Poul", cases: 1 },
  { name: "Gurpreet Singh", cases: 1 },
  { name: "Fareena Jameel", cases: 1 },
  { name: "Pervez", cases: 1 },
  { name: "Haider Ali", cases: 1 },
  { name: "Vasudha", cases: 1 },
  { name: "Mr.Prabhat", cases: 1 },
  { name: "Mr.Ranjeet", cases: 1 },
  { name: "Nittin sharma", cases: 1 },
  { name: "Imtiaz", cases: 1 },
  { name: "Hamza muneer", cases: 1 },
  { name: "Mahender Singh", cases: 1 },
  { name: "Lt.Col.Shyam Panigrahi", cases: 1 },
  { name: "Ms.Pirya", cases: 1 },
  { name: "Ms.Parwati", cases: 1 },
  { name: "Anus Khan", cases: 1 },
  { name: "Dr.Veena Chaudhry", cases: 1 },
  { name: "Mr.Farhaz", cases: 1 },
  { name: "Parjith", cases: 1 },
  { name: "Mr.Manish Kala", cases: 1 },
  { name: "WR", cases: 1 },
  { name: "Sudhakar Verma", cases: 1 },
  { name: "Saim", cases: 1 },
  { name: "Ms.Memoona Khatun", cases: 1 },
  { name: "Ubaid", cases: 1 },
  { name: "Mr.Harwinder Singh", cases: 1 },
  { name: "Jahnvi Aggarwal", cases: 1 },
  { name: "Rashika", cases: 1 },
  { name: "Mr.Arvind Saluja", cases: 1 },
  { name: "Mr.Sunil Malhotra", cases: 1 },
  { name: "Justice Deepak Varma", cases: 1 },
  { name: "Anu sharma", cases: 1 },
  { name: "Aman Aggarwal", cases: 1 },
  { name: "Dilshad Anwar", cases: 1 },
  { name: "Subhah Singh", cases: 1 },
  { name: "Manav Mehra", cases: 1 },
  { name: "Mr.Bhopal Dutt", cases: 1 },
  { name: "Mr.Veshpal Sharma", cases: 1 },
  { name: "Khateeb", cases: 1 },
  { name: "Surender Arora", cases: 1 },
  { name: "B.S Saini", cases: 1 },
  { name: "Junaid", cases: 1 },
  { name: "Zahid", cases: 1 },
  { name: "Hannan", cases: 1 },
  { name: "Ms.Mamoona", cases: 1 },
  { name: "Farina", cases: 1 },
  { name: "Ms.Mani", cases: 1 },
  { name: "Yashpal Sharma", cases: 1 },
  { name: "Mr.Sudhir Juneja", cases: 1 },
  { name: "Ms.Kavita", cases: 1 },
  { name: "Ms.Ishika", cases: 1 },
  { name: "Ms.Bharti Bhardwaj", cases: 1 },
  { name: "Mr.Avneet", cases: 1 },
  { name: "Aman Khan", cases: 1 },
  { name: "Mr.Manoj Singh", cases: 1 },
  { name: "Ms.Malvika Sinha", cases: 1 },
  { name: "Mr.Nand Kishor", cases: 1 },
  { name: "L.V Gaur", cases: 1 },
  { name: "Mr.Ajay Ahuja", cases: 1 },
  { name: "Mohommad Rehan", cases: 1 },
  { name: "Adnan", cases: 1 },
  { name: "Mrs.Alka", cases: 1 },
  { name: "Mr.Pappu", cases: 1 },
  { name: "Ms.Madhu", cases: 1 },
  { name: "Mr.Sanjeev Batra", cases: 1 },
  { name: "Pankaj", cases: 1 },
  { name: "Shakti Chopra", cases: 1 },
  { name: "Akhil Sharma", cases: 1 },
  { name: "Rameshwar", cases: 1 },
  { name: "Mr.Rupak", cases: 1 },
  { name: "Hari Chand", cases: 1 },
  { name: "Mr.Ram ji lal meena", cases: 1 },
  { name: "Mr.Hitesh Khanna", cases: 1 },
  { name: "Mohammad Shehzad", cases: 1 },
  { name: "Sujit Kumar", cases: 1 },
  { name: "Ms.Devna Arora", cases: 1 },
  { name: "Shahrukh", cases: 1 },
  { name: "Sandeep Midha", cases: 1 },
  { name: "Mr.Manish Khandelwal", cases: 1 },
  { name: "Mr.Nanna", cases: 1 },
  { name: "Mr.K D Dogra", cases: 1 },
  { name: "Vineeta Kadyan", cases: 1 },
  { name: "Mr.Kallan", cases: 1 },
  { name: "G.P Singh Bakshi", cases: 1 },
  { name: "Saud", cases: 1 },
  { name: "Liza", cases: 1 },
  { name: "Mr.Gurjeet", cases: 1 },
  { name: "Mr.Naved Zahur", cases: 1 },
  { name: "H.C. JagSharan", cases: 1 },
  { name: "Priyanka Jain", cases: 1 },
  { name: "ASI Bale Singh", cases: 1 },
  { name: "Mr.Prithwiraj", cases: 1 },
  { name: "Dr.Sukhdev Singh", cases: 1 },
  { name: "Mohammad Salik", cases: 1 },
  { name: "Deepak Verma", cases: 1 },
  { name: "Izhan Khan", cases: 1 },
  { name: "Noman", cases: 1 },
  { name: "Sewa Kutir", cases: 1 },
  { name: "Smita Chaudhry", cases: 1 },
  { name: "Altaf Rehman", cases: 1 },
  { name: "Ms.Poonam Manjal", cases: 1 },
  { name: "Nittin Jawa", cases: 1 },
  { name: "Nabeel", cases: 1 },
  { name: "Nishant", cases: 1 },
  { name: "Muhammad Fahad", cases: 1 },
  { name: "Ajit Singh", cases: 1 },
  { name: "Vicky", cases: 1 },
  { name: "Vineet Kumar Singh", cases: 1 },
  { name: "M. Faateh", cases: 1 },
  { name: "KP Handa", cases: 1 },
  { name: "Mhod. Naeem", cases: 1 },
  { name: "Rohan Panday", cases: 1 },
  { name: "Mr.Arun Talwar", cases: 1 },
  { name: "Muhammad Saad", cases: 1 },
  { name: "Humair Khan", cases: 1 },
  { name: "Manish Gahalout", cases: 1 },
  { name: "Sidharth", cases: 1 },
  { name: "Muhammad saddam", cases: 1 },
  { name: "Mohd. Faateh", cases: 1 },
  { name: "Mohd. Ubaid", cases: 1 },
  { name: "Deepak dholakia", cases: 1 },
  { name: "Muhammad Bilal", cases: 1 },
  { name: "Ripudaman Bbhardwaj", cases: 1 },
  { name: "Samohan", cases: 1 },
  { name: "Anis ur Rehman", cases: 1 },
  { name: "Master Adnan", cases: 1 },
  { name: "Nimisha", cases: 1 },
  { name: "HC Chanchal Singh", cases: 1 },
  { name: "PM House", cases: 1 },
  { name: "M. Shakir", cases: 1 },
  { name: "Avita", cases: 1 },
  { name: "Faizaan", cases: 1 },
  { name: "Naser", cases: 1 },
  { name: "Shabnam", cases: 1 },
  { name: "Himanshu Malhotra", cases: 1 },
  { name: "Manvil Kujur", cases: 1 },
  { name: "OHB-2", cases: 1 },
  { name: "Reliance", cases: 1 },
  { name: "Aishan Sharma", cases: 1 },
  { name: "Than Kachan", cases: 1 },
  { name: "Ujjwal Singh", cases: 1 },
  { name: "Parasher", cases: 1 },
  { name: "Mohd. Billal", cases: 1 },
  { name: "Salmaan", cases: 1 },
  { name: "Suresh Sharma", cases: 1 },
  { name: "Narender Singh", cases: 1 },
  { name: "KS Arsh", cases: 1 },
  { name: "Juvenile Jail", cases: 1 },
  { name: "Saraswati Music College", cases: 1 },
  { name: "Balbir Gupta", cases: 1 },
  { name: "Madhav", cases: 1 },
  { name: "Ms.Bharti Kapoor", cases: 1 },
  { name: "Mohd. Faizaan", cases: 1 },
  { name: "Mohd. Javed", cases: 1 },
  { name: "Vivek", cases: 1 },
  { name: "Mohd. Anees", cases: 1 },
  { name: "The Manager", cases: 1 },
  { name: "Divvya Patras", cases: 1 },
  { name: "Prem Singh", cases: 1 },
  { name: "Mohd. Amjad", cases: 1 },
  { name: "Mohd. Saif", cases: 1 },
  { name: "Mahd. Atif", cases: 1 },
  { name: "Mohd Tawheed", cases: 1 },
  { name: "Hafeezur Rehman", cases: 1 },
  { name: "Mehhul", cases: 1 },
  { name: "Veer Singh Tomar", cases: 1 },
  { name: "Humaam", cases: 1 },
  { name: "Kid of School", cases: 1 },
  { name: "Mohd. Sameer", cases: 1 },
  { name: "Mohd Arshad", cases: 1 },
  { name: "Mohammad Saleem", cases: 1 },
  { name: "R.N. Puri", cases: 1 },
  { name: "Salik Rehman", cases: 1 },
  { name: "Ajay Singh Rawat", cases: 1 },
  { name: "Rajesh", cases: 1 },
  { name: "Santosh Kumar", cases: 1 },
  { name: "Shahid Khan", cases: 1 },
  { name: "Fahad", cases: 1 },
  { name: "Rohit", cases: 1 },
  { name: "V.V. Iyenger", cases: 1 },
  { name: "Mohd Hamza", cases: 1 },
  { name: "Amit", cases: 1 },
  { name: "Mohd Fahad", cases: 1 },
  { name: "Teacher Training Institute", cases: 1 },
  { name: "Arvind Kumar", cases: 1 },
  { name: "Rama Shanker", cases: 1 },
  { name: "Farhaan", cases: 1 },
  { name: "Kavin Jawa", cases: 1 },
  { name: "Aaditi Saxena", cases: 1 },
  { name: "Nazneen", cases: 1 },
  { name: "Bhagwat Parsad", cases: 1 },
  { name: "Gaurav Sharma", cases: 1 },
  { name: "Somesh", cases: 1 },
  { name: "Rahul", cases: 1 },
  { name: "G.P. Alagh", cases: 1 },
  { name: "Sanjay Singh", cases: 1 },
  { name: "Govt. Girls School", cases: 1 },
  { name: "Jagdeep Singh", cases: 1 },
  { name: "Izhaan", cases: 1 },
  { name: "Master Arif", cases: 1 },
  { name: "Ms.Gurleen Kaur", cases: 1 },
  { name: "Wildlife Rescue", cases: 1 },
  { name: "S.I. Rohit", cases: 1 },
  { name: "ASI Bajran Lal", cases: 1 },
  { name: "Master Arsalaan", cases: 1 },
  { name: "Ms.Tanya", cases: 1 },
  { name: "Mster Tanish", cases: 1 },
  { name: "Mr.Mani Ram", cases: 1 },
  { name: "Mr.Vijay Saini", cases: 1 },
  { name: "Bird Hospital, Prem Bhavan", cases: 1 },
  { name: "Denish Kumar", cases: 1 },
  { name: "Sanjay Ghanhi Hospital", cases: 1 },
  { name: "Master Ziarat", cases: 1 },
  { name: "D.O.", cases: 1 },
  { name: "SPG", cases: 1 },
  { name: "Master Parul", cases: 1 },
  { name: "Sobhan Gandhi", cases: 1 },
  { name: "Bittu", cases: 1 },
  { name: "Simmi Bhagat", cases: 1 },
  { name: "Matebul", cases: 1 },
  { name: "Ms.Anchal Jain", cases: 1 },
  { name: "S. I. Kiran Chand", cases: 1 },
  { name: "Parmar Ranjan", cases: 1 },
  { name: "P. S. D. B Gupta Road", cases: 1 },
  { name: "Mr.M. Ateeb", cases: 1 },
  { name: "SS Jain Trust", cases: 1 },
  { name: "HC Banvari Lal", cases: 1 },
  { name: "DCP Office", cases: 1 },
  { name: "Switzerland Embassy", cases: 1 },
  { name: "Kulvinder Singh", cases: 1 },
  { name: "Mohammad Azad", cases: 1 },
  { name: "Aza,m", cases: 1 },
  { name: "Kameshwar Singh", cases: 1 },
  { name: "Ramesh Singh", cases: 1 },
  { name: "M. Farhan", cases: 1 },
  { name: "Mithuraj desai", cases: 1 },
  { name: "Alok Bahadur", cases: 1 },
  { name: "Mental Hospital, Shahdra", cases: 1 },
  { name: "Shubh Laxmi", cases: 1 },
  { name: "Mohammad Haroon", cases: 1 },
  { name: "Sanjiv Kaushal", cases: 1 },
  { name: "Sajiv Koushal", cases: 1 },
  { name: "DJB", cases: 1 },
  { name: "Virender Singh Shekhawat", cases: 1 },
  { name: "Abhishek Chatterji", cases: 1 },
  { name: "Kawaljeet Kaur", cases: 1 },
  { name: "Ekansh Mishra", cases: 1 },
  { name: "Sikendar Waseem", cases: 1 },
  { name: "Dhiraj Tiwari", cases: 1 },
  { name: "Vikas", cases: 1 },
  { name: "Ram Gopal", cases: 1 },
  { name: "Anmol Robinson", cases: 1 },
  { name: "Ongyal Bhatia", cases: 1 },
  { name: "Saniya", cases: 1 },
  { name: "Anand Kumar", cases: 1 },
  { name: "Hemant Saraswati", cases: 1 },
  { name: "Mohammad Sajid", cases: 1 },
  { name: "Shilpa Chaudhary", cases: 1 },
  { name: "Kailash Chand Ji", cases: 1 },
  { name: "V. T. C Anglor Arabic School", cases: 1 },
  { name: "Nibha Khorwal", cases: 1 },
  { name: "Anglor Arebik School", cases: 1 },
  { name: "Office of Comissioner of Disabilities", cases: 1 },
  { name: "Surendra", cases: 1 },
  { name: "Vikas Sethi", cases: 1 },
  { name: "Kamran Khan", cases: 1 },
  { name: "Sunaina Gogoi", cases: 1 },
  { name: "Bharti Tonk", cases: 1 },
  { name: "Shashank", cases: 1 },
  { name: "Mehroon", cases: 1 },
  { name: "Afnan", cases: 1 },
  { name: "Shyamveer", cases: 1 },
  { name: "Garima Panwar", cases: 1 },
  { name: "Ashok Harshwardhan", cases: 1 },
  { name: "Nitin Verma", cases: 1 },
  { name: "M. K. Gupta", cases: 1 },
  { name: "Furqana", cases: 1 },
  { name: "Shalender Kumar", cases: 1 },
  { name: "Varsha Sharma", cases: 1 },
  { name: "Harsh Parsad", cases: 1 },
  { name: "H C Ajab Singh(1174/PCR)", cases: 1 },
  { name: "Mastwr Arshan", cases: 1 },
  { name: "Alka Singh", cases: 1 },
  { name: "Bhawesh Pant", cases: 1 },
  { name: "Mohshin Shahzad", cases: 1 },
  { name: "Uttam Chand", cases: 1 },
  { name: "Jaya Singh", cases: 1 },
  { name: "Mohan Krishna Sengar", cases: 1 },
  { name: "MCD Veternery Department", cases: 1 },
  { name: "Northen Railways", cases: 1 },
  { name: "Pusa Institute", cases: 1 },
  { name: "Ex MLA Bitta", cases: 1 },
  { name: "Juvinile Jail", cases: 1 },
  { name: "Saket Sports Complex", cases: 1 },
  { name: "Lady Harding Medical Collage", cases: 1 },
  { name: "Gurjeet Singh", cases: 1 },
  { name: "Head Constable Mahesh Singh", cases: 1 },
  { name: "Master Hamza", cases: 1 },
  { name: "People For Animals", cases: 1 },
  { name: "Subedar Lal Singh", cases: 1 },
  { name: "People For Animals Faridabad", cases: 1 },
  { name: "Bhagwat Prasad", cases: 1 },
  { name: "Police Headquarters", cases: 1 },
  { name: "Bal Chand Morya", cases: 1 },
  { name: "Fire Station Filmistan", cases: 1 },
  { name: "Inspector Manoj", cases: 1 },
  { name: "Deepak Khaitan", cases: 1 },
  { name: "Police Station Selampur", cases: 1 },
  { name: "Sri Fort Sports Complex", cases: 1 },
  { name: "Vasundhra", cases: 1 },
  { name: "Surjeet", cases: 1 },
  { name: "Narinder Singh", cases: 1 },
  { name: "Varun", cases: 1 },
  { name: "Rohin Bharti", cases: 1 },
  { name: "Shatrughan Pal Rai", cases: 1 },
  { name: "Motish Singh", cases: 1 },
  { name: "Mayank Sharma", cases: 1 },
  { name: "Himanshu Yadav", cases: 1 },
  { name: "Shalini Kapoor", cases: 1 },
  { name: "Rajiv Kumar Singh", cases: 1 },
  { name: "Jagdish", cases: 1 },
  { name: "Rohtash Kashyap", cases: 1 },
  { name: "Nivedita Varma", cases: 1 },
  { name: "Gaurav Malik", cases: 1 },
  { name: "Adil Shaheen", cases: 1 },
  { name: "Neena Jain", cases: 1 },
  { name: "Mukul Adhana", cases: 1 },
  { name: "Ignative Justice", cases: 1 },
  { name: "Farhat Raja", cases: 1 },
  { name: "Mohit Garg", cases: 1 },
  { name: "Prvesh", cases: 1 },
  { name: "Pawan Tyagi", cases: 1 },
  { name: "Ashish Kumar", cases: 1 },
  { name: "Dinesh Dogra", cases: 1 },
  { name: "Abhinav Khetarpal", cases: 1 },
  { name: "SK Gupta", cases: 1 },
  { name: "Versha Chopra", cases: 1 },
  { name: "Anurag Sharma", cases: 1 },
  { name: "Rajini", cases: 1 },
  { name: "Om Prakash Gulati", cases: 1 },
  { name: "Krishna Kumar Pathak", cases: 1 },
  { name: "Anurag Garg", cases: 1 },
  { name: "Wilson", cases: 1 },
  { name: "Yogesh Sharma", cases: 1 },
  { name: "Devended Rohit Shakti", cases: 1 },
  { name: "Dhiraj Garg", cases: 1 },
  { name: "Dheeraj", cases: 1 },
  { name: "Gaurav Pratap Singh", cases: 1 },
  { name: "Anomita Goswami", cases: 1 },
  { name: "RK Gatam", cases: 1 },
  { name: "Surender", cases: 1 },
  { name: "Deepak Bansal", cases: 1 },
  { name: "Devendra Kumar", cases: 1 },
  { name: "Vidushi Khanna", cases: 1 },
  { name: "Aastha Vidyasagar", cases: 1 },
  { name: "Shreya Srivastava", cases: 1 },
  { name: "Ritika", cases: 1 },
  { name: "Milan Vihar Society", cases: 1 },
  { name: "Aya Singh", cases: 1 },
  { name: "DJB Ramlila Ground", cases: 1 },
  { name: "Dinesh", cases: 1 },
  { name: "Shakti Nagar", cases: 1 },
  { name: "Maujpur", cases: 1 },
  { name: "Punjabi Bagh West", cases: 1 },
  { name: "Hudson Lane", cases: 1 },
  { name: "CPWD", cases: 1 },
  { name: "Archies Ltd.", cases: 1 },
  { name: "Principal", cases: 1 },
  { name: "Manisha", cases: 1 },
  { name: "MCD Control Room", cases: 1 },
  { name: "St. Stephen's College", cases: 1 },
  { name: "Harish", cases: 1 },
  { name: "Savita Chaudhary", cases: 1 },
  { name: "Gaurav Kumar", cases: 1 },
  { name: "Kamla Prasad", cases: 1 },
  { name: "Anuj", cases: 1 },
  { name: "Dhiraj Singh", cases: 1 },
  { name: "Shruti", cases: 1 },
  { name: "BSES Office", cases: 1 },
  { name: "Global Properties", cases: 1 },
  { name: "Nutan", cases: 1 },
  { name: "Rajeev Chopra", cases: 1 },
  { name: "Hardeep Kaur", cases: 1 },
  { name: "Man Mohan", cases: 1 },
  { name: "Uma Muthu Krishnan", cases: 1 },
  { name: "Mohammad Shamim", cases: 1 },
  { name: "Shweta Prajapati", cases: 1 },
  { name: "Ramesh Kumar", cases: 1 },
  { name: "Arun Bhasin", cases: 1 },
  { name: "Naved", cases: 1 },
  { name: "Ritu Atwari", cases: 1 },
  { name: "Aseem Goel", cases: 1 },
  { name: "Tanmay Sharma", cases: 1 },
  { name: "Chetan Kumar", cases: 1 },
  { name: "Vshilj Sigh Kushwala", cases: 1 },
  { name: "Sandeep Kumar", cases: 1 },
  { name: "SS Tomar", cases: 1 },
  { name: "Pramod Chaudhary", cases: 1 },
  { name: "Jai Prakash", cases: 1 },
  { name: "Sanya", cases: 1 },
  { name: "Anubhav Singh", cases: 1 },
  { name: "Manpreet", cases: 1 },
  { name: "Vikas Sharma", cases: 1 },
  { name: "Deepak Kumar", cases: 1 },
  { name: "Amir", cases: 1 },
  { name: "Sonu", cases: 1 },
  { name: "Braham Pal", cases: 1 },
  { name: "Dixita Sharma", cases: 1 },
  { name: "Yash Pal Batra", cases: 1 },
  { name: "Ayesha Parveen", cases: 1 },
  { name: "Tushar Sharma", cases: 1 },
  { name: "Manish Kumar", cases: 1 },
  { name: "Mahesh", cases: 1 },
  { name: "Rakesh", cases: 1 },
  { name: "Sneh Lata Panwar", cases: 1 },
  { name: "Sanjay Kumar", cases: 1 },
  { name: "Farida/PCR", cases: 1 },
  { name: "BR Sharma", cases: 1 },
  { name: "Jasveer Singh", cases: 1 },
  { name: "Raghuvir", cases: 1 },
  { name: "Ashok Kumar", cases: 1 },
  { name: "Aakaash", cases: 1 },
  { name: "Shivam Dua", cases: 1 },
  { name: "Jiya", cases: 1 },
  { name: "Praveen Jain", cases: 1 },
  { name: "Krishna", cases: 1 },
  { name: "Pandey", cases: 1 },
  { name: "Ekta", cases: 1 },
  { name: "Booster Pumping Station", cases: 1 },
  { name: "Shyam Singh", cases: 1 },
  { name: "Gajendra Kumar", cases: 1 },
  { name: "Ankur Sharma", cases: 1 },
  { name: "Gaurav Fateh Singh", cases: 1 },
  { name: "Kunal Sharma", cases: 1 },
  { name: "Mohammad Hamza", cases: 1 },
  { name: "Chadrashekhar", cases: 1 },
  { name: "Presidium School", cases: 1 },
  { name: "A.P. Singh", cases: 1 },
  { name: "Maam Chand", cases: 1 },
  { name: "Parvinder Malik", cases: 1 },
  { name: "K.K. Dwivedi", cases: 1 },
  { name: "Hansraj", cases: 1 },
  { name: "Bhabhani Dash", cases: 1 },
  { name: "Avdesh Tomer", cases: 1 },
  { name: "Shikha Pahwa", cases: 1 },
  { name: "Satpal Pehelwan", cases: 1 },
  { name: "Rishi Jain", cases: 1 },
  { name: "Salman Alvi", cases: 1 },
  { name: "Joginder Singh", cases: 1 },
  { name: "Narender Kumar Arora", cases: 1 },
  { name: "Hardeep Rana", cases: 1 },
  { name: "Vijay Singh", cases: 1 },
  { name: "Verhan Khanna", cases: 1 },
  { name: "Ishant Jain", cases: 1 },
  { name: "Umesh Kumar", cases: 1 },
  { name: "Police Staion Sabzi Mandi", cases: 1 },
  { name: "T.S Satya Nath", cases: 1 },
  { name: "Madan", cases: 1 },
  { name: "Rabindar Nath Dhawa", cases: 1 },
  { name: "Gyan Singh", cases: 1 },
  { name: "Extra Assistant Director", cases: 1 },
  { name: "Shiv Ram", cases: 1 },
  { name: "Manish Dutt", cases: 1 },
  { name: "Imran Khan", cases: 1 },
  { name: "Parveen Kumar", cases: 1 },
  { name: "Renu", cases: 1 },
  { name: "Nikhil Chandra", cases: 1 },
  { name: "Farzan", cases: 1 },
  { name: "MCD Dispensary", cases: 1 },
  { name: "Dharamveer", cases: 1 },
  { name: "Nanna", cases: 1 },
  { name: "Vivek Kumar", cases: 1 },
  { name: "Sibinder Gupta", cases: 1 },
  { name: "Sajib Kumar", cases: 1 },
  { name: "Dharmender Kumar", cases: 1 },
  { name: "Savita", cases: 1 },
  { name: "Raghubir", cases: 1 },
  { name: "Ahsan", cases: 1 },
  { name: "Bittu Baskey", cases: 1 },
  { name: "Baba Garments", cases: 1 },
  { name: "Govt. Boys School", cases: 1 },
  { name: "Aadil", cases: 1 },
  { name: "Sami", cases: 1 },
  { name: "Ruchin Mehra", cases: 1 },
  { name: "Mohd. Masood", cases: 1 },
  { name: "Mohd. Yousuf", cases: 1 },
  { name: "Lal Bahadur Yadav", cases: 1 },
  { name: "Mamta Ran", cases: 1 },
  { name: "DCP North West", cases: 1 },
  { name: "Shivander Tomar", cases: 1 },
  { name: "Gourav", cases: 1 },
  { name: "Sakib", cases: 1 },
  { name: "Sukh Deep Singh", cases: 1 },
  { name: "Asad", cases: 1 },
  { name: "Amit And Kapil", cases: 1 },
  { name: "Subedar", cases: 1 },
  { name: "Rakesh Tiwari", cases: 1 },
  { name: "Dushyant Sharma", cases: 1 },
  { name: "Vibha Sharma", cases: 1 },
  { name: "Harshwardhan", cases: 1 },
  { name: "A.B. Lal", cases: 1 },
  { name: "Mahinder Singh", cases: 1 },
  { name: "Gourav Yadav", cases: 1 },
  { name: "Abhishake Khanna", cases: 1 },
  { name: "Jag Mohan", cases: 1 },
  { name: "Aman Preet", cases: 1 },
  { name: "Tarun Kumar", cases: 1 },
  { name: "Nisha", cases: 1 },
  { name: "Students Of St. Stephan College", cases: 1 },
  { name: "Kishan Singh", cases: 1 },
  { name: "Mohd. Amir", cases: 1 },
  { name: "Hemant Sharma", cases: 1 },
  { name: "Aryan Singh", cases: 1 },
  { name: "Shreya", cases: 1 },
  { name: "Malkhan Singh", cases: 1 },
  { name: "I.P College", cases: 1 },
  { name: "Prena", cases: 1 },
  { name: "Director Of Education", cases: 1 },
  { name: "Virendra", cases: 1 },
  { name: "Jayvardhan Joju", cases: 1 },
  { name: "Kabir", cases: 1 },
  { name: "Rajendra Maurya", cases: 1 },
  { name: "Praveen", cases: 1 },
  { name: "Sarthik", cases: 1 },
  { name: "Mohan Gopal", cases: 1 },
  { name: "Chetna", cases: 1 },
  { name: "Viran Khana", cases: 1 },
  { name: "Azad Saini", cases: 1 },
  { name: "R.M. Shukla", cases: 1 },
  { name: "Santosh", cases: 1 },
  { name: "Simran Arora", cases: 1 },
  { name: "Abhinav", cases: 1 },
  { name: "Ishika", cases: 1 },
  { name: "Amit Singh", cases: 1 },
  { name: "Shan Mukhan", cases: 1 },
  { name: "Praveen Kumar", cases: 1 },
  { name: "Rahil", cases: 1 },
  { name: "Rose Amma", cases: 1 },
  { name: "Jacob", cases: 1 },
  { name: "George", cases: 1 },
  { name: "Sagar", cases: 1 },
  { name: "Mahesh Sharma", cases: 1 },
  { name: "Avinash Sinha", cases: 1 },
  { name: "Jatin", cases: 1 },
  { name: "Kamal Singh", cases: 1 },
  { name: "Sumant", cases: 1 },
  { name: "Jamil Ur Rehman", cases: 1 },
  { name: "Naveen", cases: 1 },
  { name: "Chuhan", cases: 1 },
  { name: "Chetan", cases: 1 },
  { name: "Sambhav Jain", cases: 1 },
  { name: "Embassy Of Republic Of Turkey", cases: 1 },
  { name: "Gurvender Singh", cases: 1 },
  { name: "Nilza", cases: 1 },
  { name: "Shubham", cases: 1 },
  { name: "Kirpa Ashram", cases: 1 },
  { name: "Gul Mohar", cases: 1 },
  { name: "Aditya Rathor", cases: 1 },
  { name: "Sohan Kashyap", cases: 1 },
  { name: "Manish", cases: 1 },
  { name: "Archit Jain", cases: 1 },
  { name: "Preeti", cases: 1 },
  { name: "Mohammad Tarik", cases: 1 },
  { name: "D.R. Sharma", cases: 1 },
  { name: "Chiramji Lal", cases: 1 },
  { name: "Manoj", cases: 1 },
  { name: "Santosh Kumar Singh", cases: 1 },
  { name: "Aman Goyal", cases: 1 },
  { name: "Vishwas Bahl", cases: 1 },
  { name: "Avinash Kumar", cases: 1 },
  { name: "Anil Jain", cases: 1 },
  { name: "Javed", cases: 1 },
  { name: "Mohammad Shakeel", cases: 1 },
  { name: "P.S Burari", cases: 1 },
  { name: "A.C.P  Crime", cases: 1 },
  { name: "Office Of The Commissioner Of Disabilities", cases: 1 },
  { name: "Sarvodya Bal Vidyalaya", cases: 1 },
  { name: "ACP Crime Office", cases: 1 },
  { name: "A.S.I Manoj", cases: 1 },
  { name: "A.S.I Dinesh Kumar", cases: 1 },
  { name: "Abhay Danam Bird Hospital", cases: 1 },
  { name: "Anuj Sharma", cases: 1 },
  { name: "Justice Deepak Gupta", cases: 1 },
  { name: "ASI Dilbagh Singh", cases: 1 },
  { name: "Goudhan Sewa Samiti", cases: 1 },
  { name: "Sukh Swarup Birds Care Foundation", cases: 1 },
  { name: "ASI Chandarpal", cases: 1 },
  { name: "S.O. Bheem Dutt", cases: 1 },
  { name: "OHB Sewa Kutir", cases: 1 },
  { name: "Security Guard", cases: 1 },
  { name: "Twinkle Gogia", cases: 1 },
  { name: "Wildlife Inspector R.R Meena", cases: 1 },
  { name: "HC Mohd. Yameen", cases: 1 },
  { name: "Hrjdyansh Jha", cases: 1 },
  { name: "Insp. Dasan", cases: 1 },
  { name: "Saurabh Pandey", cases: 1 },
  { name: "H.C. Pradeep", cases: 1 },
  { name: "Hotel Anna INN", cases: 1 },
  { name: "WL Insp. B. Dasan", cases: 1 },
  { name: "F.G Karnel Singh", cases: 1 },
  { name: "HC Pradeep", cases: 1 },
  { name: "Shivangi Prasad", cases: 1 },
  { name: "Aas Foundation", cases: 1 },
  { name: "Kannan Animal Welfare", cases: 1 },
  { name: "Mrs.Swayambika", cases: 1 },
  { name: "Asheesh", cases: 1 },
  { name: "New Delhi Nature Socity", cases: 1 },
  { name: "Voice Of Voiceless", cases: 1 },
  { name: "DCP", cases: 1 },
  { name: "Ms.Soma", cases: 1 },
  { name: "Golden Properties", cases: 1 },
  { name: "Mr.Fazil", cases: 1 },
  { name: "Mohd. Shad", cases: 1 },
  { name: "Mohd Asad", cases: 1 },
  { name: "Md Maaz", cases: 1 },
  { name: "Mr.Dwarika Tiwari", cases: 1 },
  { name: "Mohammad Imran", cases: 1 },
  { name: "Karan Foundation", cases: 1 },
  { name: "Md. Adeeb", cases: 1 },
  { name: "Beil A Tail", cases: 1 },
  { name: "Sahibe Alam", cases: 1 },
  { name: "Mahvir Swami Bird House & Hospital", cases: 1 },
  { name: "Kshitij Dardari", cases: 1 },
  { name: "North Division", cases: 1 },
  { name: "Payal Singh", cases: 1 },
  { name: "M/s. Naighbaourhood Food", cases: 1 },
  { name: "Vidya Sagar Jeevdya Parivar Trust", cases: 1 },
  { name: "M/s. Wing and Tails Foundation", cases: 1 },
  { name: "Office Of Lieutenant Governor", cases: 1 },
  { name: "Pream Khanna", cases: 1 },
  { name: "Neophron Charity Birds Hospital", cases: 1 },
  { name: "Mohd Arbaz", cases: 1 },
  { name: "Mohd Mohsin", cases: 1 },
  { name: "Vidya Sagar Jeev Daya Trust", cases: 1 },
  { name: "Vidya Sagar Jeev Daya Parivaar Trust", cases: 1 },
  { name: "Wing and Tail Foundation", cases: 1 },
  { name: "Amraah Foundation", cases: 1 },
  { name: "Gyandeep Vidya Bhawan", cases: 1 },
  { name: "Kishan Prasad Bhandari", cases: 1 },
  { name: "Gopi Kumar", cases: 1 },
  { name: "Ashutosh Grover", cases: 1 },
  { name: "Chander Bhan", cases: 1 },
  { name: "Mr.. Mehfuz", cases: 1 },
  { name: "M/s. Vijay Ballabh Bird Hospital", cases: 1 },
  { name: "Jay Kumar", cases: 1 },
  { name: "M/s. Amarah Foundation", cases: 1 },
  { name: "Arun Raina", cases: 1 },
  { name: "NK Jain", cases: 1 },
  { name: "Willife & Habitat Trust", cases: 1 },
];

export const YEARLY_INTAKE: YearRow[] = [
  { year: 1930, cases: 3 },
  { year: 1931, cases: 6 },
  { year: 2002, cases: 1573 },
  { year: 2010, cases: 119 },
  { year: 2011, cases: 1249 },
  { year: 2012, cases: 586 },
  { year: 2013, cases: 1110 },
  { year: 2014, cases: 1227 },
  { year: 2015, cases: 1994 },
  { year: 2016, cases: 2770 },
  { year: 2017, cases: 2112 },
  { year: 2018, cases: 2090 },
  { year: 2019, cases: 2135 },
  { year: 2020, cases: 2489 },
  { year: 2021, cases: 2774 },
  { year: 2022, cases: 3385 },
  { year: 2023, cases: 3402 },
  { year: 2024, cases: 3670 },
  { year: 2025, cases: 4184 },
  { year: 2026, cases: 1810 },
  { year: 2027, cases: 9 },
  { year: 2028, cases: 2 },
  { year: 2029, cases: 5 },
];
