export interface Species {
  slug: string;
  name: string;
  scientificName: string;
  conservationStatus: string;
  iucnColor: string;
  percentage: string;
  annualCases: string;
  category: string;
  habitat: string;
  range: string;
  diet: string;
  size: string;
  behavior: string;
  threatsInDelhi: string;
  description: string;
  funFact: string;
  /** Primary image for hero/listing. Path relative to /public (e.g. "/species/shikra-face.jpg") */
  image?: string;
  /** Additional images for the gallery on the species detail page */
  images?: { src: string; alt: string }[];
  /** CSS object-position for the primary image (default: "center") */
  imagePosition?: string;
  /** Single video clip for the species detail page (path relative to /public) */
  video?: { src: string; caption: string };
  /** Multiple video clips for the species detail page */
  videos?: { src: string; caption: string }[];
}

export const SPECIES_LIST: Species[] = [
  {
    slug: "black-kite",
    name: "Black Kite",
    scientificName: "Milvus migrans",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~80%",
    annualCases: "~3,200/year",
    category: "Raptor",
    habitat: "Urban areas, open country near water, landfills, and markets. Delhi's Old City neighborhoods are a global hotspot for Black Kite density.",
    range: "Widespread across Europe, Asia, Africa, and Australasia. The Indian subspecies (M. m. govinda) is a year-round resident of the Indian subcontinent.",
    diet: "Opportunistic scavenger and predator. Feeds on fish, rodents, insects, scraps from markets, and waste. Often seen soaring over the Yamuna River and Delhi's landfills.",
    size: "Body length 47–60 cm, wingspan 120–153 cm, weight 400–900g. Medium-sized raptor with a distinctive forked tail.",
    behavior: "Highly social and gregarious. Nests on trees, ledges, and buildings in Delhi. Famous for their spectacular aerial acrobatics — swooping, diving, and kiting on thermal updrafts over the city.",
    threatsInDelhi: "Manja (glass-coated kite string) is the #1 threat — causes severe wing lacerations during festivals. Also electrocution from wet power lines during monsoon, vehicle collisions, poisoning from contaminated food at landfills, and habitat loss from rapid urbanization.",
    description: "The Black Kite is Delhi's most iconic raptor and the core of Wildlife Rescue's mission. Millions live in the city, making Delhi one of the highest concentrations of raptors in any urban area worldwide. Their presence is a barometer of the city's ecological health.",
    funFact: "Delhi has one of the highest densities of Black Kites in the world — estimated at over 5,000 birds in the city alone. They've lived alongside Delhi's human population for centuries.",
    videos: [
      { src: "/treatments/laser-wound-management.mp4", caption: "A Black Kite receiving laser wound therapy at Wildlife Rescue — laser treatment accelerates healing of the deep tissue lacerations caused by manja (glass-coated kite string)" },
      { src: "/treatments/kite-post-treatment.mp4", caption: "A Black Kite being gently dried in a bird dryer after wound cleaning — thermoregulation is critical for avian patients, as wet feathers can cause dangerous hypothermia" },
    ],
  },
  {
    slug: "barn-owl",
    name: "Barn Owl",
    scientificName: "Tyto alba",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~3.3%",
    annualCases: "~130/year",
    category: "Raptor",
    habitat: "Old buildings, temples, ruins, farmland edges, and cavity-rich trees. In Delhi, they favor heritage structures and abandoned buildings in older neighborhoods.",
    range: "One of the most widespread birds in the world — found on every continent except Antarctica. The Indian subspecies (T. a. stertens) is resident across the subcontinent.",
    diet: "Specialized rodent hunter. Hunts almost exclusively at night using extraordinary hearing — can locate prey in complete darkness. A single Barn Owl family can consume over 3,000 rodents per year.",
    size: "Body length 33–39 cm, wingspan 80–95 cm, weight 250–480g. Heart-shaped facial disc is distinctive.",
    behavior: "Strictly nocturnal. Silent flier due to specialized feather structure that muffles wing noise. Nests in cavities — buildings, tree hollows, and nest boxes.",
    threatsInDelhi: "Habitat loss as old buildings are demolished. Rodenticide poisoning (secondary poisoning from eating poisoned rats). Vehicle collisions at night. Superstition — some communities consider owls unlucky, leading to persecution.",
    description: "The Barn Owl is one of the most effective natural pest controllers on the planet. Their presence in Delhi should be celebrated, not feared. Wildlife Rescue treats ~130 Barn Owls annually, mostly juveniles that fall from nesting sites.",
    funFact: "A Barn Owl can hear a mouse's heartbeat from 30 feet away. Their asymmetric ears allow them to pinpoint prey in three dimensions using sound alone.",
    image: "/species/barn-owl-treatment.jpg",
    imagePosition: "left center",
    images: [
      { src: "/species/barn-owl-treatment.jpg", alt: "Barn Owl lying on examination table during treatment at Wildlife Rescue" },
    ],
    video: { src: "/species/barn-owl-video.mp4", caption: "A Barn Owl in care at Wildlife Rescue — these silent nocturnal hunters are one of the most effective natural pest controllers on the planet" },
  },
  {
    slug: "egyptian-vulture",
    name: "Egyptian Vulture",
    scientificName: "Neophron percnopterus",
    conservationStatus: "Endangered",
    iucnColor: "text-danger",
    percentage: "~0.2%",
    annualCases: "~7/year",
    category: "Raptor",
    habitat: "Open dry habitats, cliffs, and increasingly urban areas where they scavenge at dumps and slaughterhouses. In Delhi, found near the Yamuna floodplain and on the outskirts.",
    range: "Southern Europe, Africa, Middle East, and South Asia. Indian population has declined dramatically — estimated 80% decline in 3 generations.",
    diet: "Scavenger feeding on carcasses, waste, and organic refuse. One of the few birds that uses tools — drops stones on ostrich eggs to break them open.",
    size: "Body length 47–65 cm, wingspan 155–180 cm, weight 1.6–2.4 kg. Adults are distinctive white with black flight feathers and a yellow face.",
    behavior: "Often seen soaring on thermals. Relatively tolerant of humans. Nests on cliffs and building ledges. Can live 30+ years.",
    threatsInDelhi: "Diclofenac poisoning (the drug that decimated South Asia's vulture populations). Electrocution from power lines. Lead poisoning from contaminated carcasses. Habitat loss and disturbance at nesting sites.",
    description: "Every Egyptian Vulture matters. With IUCN Endangered status and populations crashing across South Asia, the individuals that Wildlife Rescue treats represent a critical contribution to species survival. We treat approximately 7 per year — each one is precious.",
    funFact: "Egyptian Vultures are one of the only birds known to use tools. They pick up stones in their beaks and throw them at ostrich eggs to crack them open — a behavior observed for thousands of years and depicted in ancient Egyptian art.",
  },
  {
    slug: "shikra",
    name: "Shikra",
    scientificName: "Accipiter badius",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~1.6%",
    annualCases: "~60/year",
    category: "Raptor",
    habitat: "Wooded areas, gardens, parks, and urban green spaces. Well-adapted to city life in Delhi — found in Lodhi Gardens, Sanjay Van, and residential areas with mature trees.",
    range: "Widespread across sub-Saharan Africa and South/Southeast Asia. Common resident across the Indian subcontinent.",
    diet: "Active predator hunting small birds, lizards, frogs, and large insects. Hunts from a perch, making short fast dashes to catch prey — a classic accipiter hunting style.",
    size: "Body length 26–30 cm, wingspan 40–55 cm, weight 75–160g. Small but fierce raptor with bright red-orange eyes.",
    behavior: "Bold and aggressive despite small size. Will defend territory against much larger birds. Fast, agile flier capable of navigating dense vegetation at speed.",
    threatsInDelhi: "Window strikes in modern buildings. Glue traps meant for rodents. Pesticide poisoning from eating contaminated insects and lizards. Nest disturbance during tree pruning.",
    description: "The Shikra is Delhi's most common small raptor — a compact, fierce predator perfectly adapted to urban life. Despite their small size, they're formidable hunters. Wildlife Rescue treats approximately 60 Shikras per year.",
    funFact: "The name 'Shikra' comes from the Hindi word 'shikari' (hunter). They were historically used in falconry across India and the Middle East — prized for their speed and agility.",
    image: "/species/shikra-face.jpg",
    images: [
      { src: "/species/shikra-face.jpg", alt: "Shikra close-up showing distinctive bright red-orange eyes and grey plumage" },
      { src: "/species/shikra-profile.jpg", alt: "Shikra being gently held during examination, showing barred breast feathers and orange eyes" },
    ],
  },
  {
    slug: "spotted-owlet",
    name: "Spotted Owlet",
    scientificName: "Athene brama",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~0.4%",
    annualCases: "~15/year",
    category: "Raptor",
    habitat: "Extremely adaptable — found in gardens, parks, old buildings, temple complexes, and even busy marketplaces. One of Delhi's most common owls.",
    range: "Resident across South and Southeast Asia, from Iran to Vietnam. Abundant across the Indian subcontinent at all elevations up to 1,400m.",
    diet: "Insects, small rodents, lizards, and small birds. Most active at dusk and dawn (crepuscular) but also hunts during the day — unusual for an owl.",
    size: "Body length 19–21 cm, weight 110–120g. Small, stocky owl with spotted plumage, bright yellow eyes, and a perpetually surprised expression.",
    behavior: "Unusually bold for an owl — often seen bobbing and weaving on branches when curious or alarmed. Nests in tree cavities, wall holes, and building crevices. Often found in pairs.",
    threatsInDelhi: "Habitat loss as old trees and buildings are removed. Vehicle strikes during dusk/dawn hunting. Superstitious persecution. Nest disturbance during construction and renovation.",
    description: "The Spotted Owlet is one of Delhi's most charismatic birds — small, bold, and endlessly entertaining. Their wide-eyed expressions and head-bobbing behavior make them favorites of birdwatchers. Wildlife Rescue treats about 15 per year.",
    funFact: "Spotted Owlets are one of the few owl species that are regularly active during daylight. They're often the first owl species that Delhi birdwatchers learn to identify — usually spotted glaring from a hole in an old wall or tree.",
    image: "/species/spotted-owlet-hero.jpg",
    images: [
      { src: "/species/spotted-owlet-hero.jpg", alt: "Spotted Owlet intense close-up showing bright yellow eyes and spotted brown plumage" },
      { src: "/species/spotted-owlet-01.jpg", alt: "Spotted Owlet perched on shelf with wide-eyed surprised expression, showing full body and spotted feathers" },
      { src: "/species/spotted-owlet-03.jpg", alt: "Spotted Owlet extreme close-up of face showing distinctive yellow eye and delicate spotted feather detail" },
    ],
  },
  {
    slug: "crested-serpent-eagle",
    name: "Crested Serpent Eagle",
    scientificName: "Spilornis cheela",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~0.2%",
    annualCases: "~10/year",
    category: "Raptor",
    habitat: "Forested areas and woodland edges. In Delhi, found in the Ridge forests (Sanjay Van, Northern Ridge) and wooded campuses. Requires mature canopy for nesting.",
    range: "Widespread across South and Southeast Asia, from India to Indonesia. Indian populations are resident.",
    diet: "Specialized snake and reptile hunter — as the name suggests. Also takes frogs, lizards, small mammals, and birds. Hunts from a high perch, watching the forest floor for movement.",
    size: "Body length 56–74 cm, wingspan 123–155 cm, weight 420–1,800g. Large, impressive eagle with a distinctive crest and bold barred pattern.",
    behavior: "Soars on thermals with a distinctive loud, piercing call — one of the most recognizable raptor calls in Indian forests. Relatively shy compared to Black Kites.",
    threatsInDelhi: "Electrocution from power lines at forest edges. Habitat loss as Delhi's Ridge forests face encroachment. Vehicle collisions on roads cutting through forested areas. Disturbance at nest sites.",
    description: "The Crested Serpent Eagle is a magnificent forest raptor that most Delhiites don't even know lives in their city. Found in Delhi's Ridge forests, they represent the wild heart of the capital. Wildlife Rescue treats about 10 per year.",
    funFact: "Their loud, ringing 'kee-kee-kee-kee' call echoing through Delhi's Ridge forests is one of the most evocative wild sounds you can hear in an Indian city. In many Southeast Asian cultures, they're considered a symbol of watchfulness and courage.",
  },
  {
    slug: "blue-rock-pigeon",
    name: "Blue Rock Pigeon",
    scientificName: "Columba livia",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~6.3%",
    annualCases: "~240/year",
    category: "Urban Bird",
    habitat: "One of the most successful urban birds worldwide. Found everywhere in Delhi — markets, temples, residential areas, railway stations, and monuments.",
    range: "Native to southern Europe, North Africa, and South Asia. Feral populations now found worldwide — possibly the most widely distributed bird in the world.",
    diet: "Seeds, grains, food scraps. Highly adaptable feeder that thrives on human food waste and deliberate feeding at temples and public spaces.",
    size: "Body length 29–37 cm, wingspan 62–72 cm, weight 238–380g. Familiar gray bird with iridescent neck feathers.",
    behavior: "Highly social and gregarious. Capable of remarkable navigation — can find their way home over hundreds of kilometers. In Delhi, they congregate at temples and feeding spots in flocks of hundreds.",
    threatsInDelhi: "Thread and manja entanglement. Glue traps. Vehicle strikes. Disease outbreaks in dense populations. Poisoning from contaminated grain.",
    description: "Once a small part of intake, the Blue Rock Pigeon is now Wildlife Rescue's #2 species at 6.3% of cases — reflecting the organization's broadening mission beyond raptors to serve all Delhi's birds in need.",
    funFact: "Despite being the 'common pigeon,' Blue Rock Pigeons are remarkable navigators. They can detect the Earth's magnetic field, use the sun as a compass, and recognize landmarks from the air — abilities that humans exploited for thousands of years using carrier pigeons.",
  },
  {
    slug: "black-eared-kite",
    name: "Black Eared Kite",
    scientificName: "Milvus migrans lineatus",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~2%",
    annualCases: "~80/year",
    category: "Raptor",
    habitat: "Open woodland, forest edges, and urban areas. In Delhi, overlaps with the Black Kite (M. m. govinda) during winter months, frequenting the Yamuna floodplain, landfills, and agricultural outskirts.",
    range: "Breeds across Central and East Asia — Siberia, Mongolia, China, Japan. Northern populations migrate south in winter, reaching the Indian subcontinent from October to March. Some individuals overwinter in Delhi.",
    diet: "Similar to Black Kite — an opportunistic scavenger and predator. Feeds on fish, small mammals, insects, and carrion. Slightly larger bill may give an edge in handling larger prey items.",
    size: "Body length 50–65 cm, wingspan 130–160 cm, weight 500–1,100g. Noticeably larger than the resident Black Kite subspecies (govinda), with darker ear coverts that give it its name.",
    behavior: "Migratory — arrives in Delhi around October and departs by March. Often mixes with resident Black Kite flocks, making identification challenging. Tends to be slightly less gregarious than govinda in urban settings.",
    threatsInDelhi: "Same as Black Kite — manja string lacerations, electrocution, vehicle collisions, and poisoning. Winter migrants face additional stress from long-distance travel and unfamiliar urban hazards. Habitat degradation at stopover sites along the Central Asian Flyway.",
    description: "The Black Eared Kite is the migratory cousin of Delhi's resident Black Kite. Taxonomists debate whether it's a full species or a subspecies (M. migrans lineatus). During winter, these larger, darker birds mix with Delhi's resident kites — and Wildlife Rescue treats them alongside their local relatives.",
    funFact: "Black Eared Kites migrate thousands of kilometers from Siberia and Mongolia to winter in India. Some individuals fitted with GPS trackers have been recorded crossing the Himalayas at altitudes above 4,000 meters — a remarkable feat for a bird that spends most of its time scavenging at ground level.",
  },
  {
    slug: "wetland-birds",
    name: "Wetland Birds",
    scientificName: "Various species",
    conservationStatus: "Mixed",
    iucnColor: "text-slate",
    percentage: "~3%",
    annualCases: "~120/year",
    category: "Wetland",
    habitat: "Marshes, riverbanks, lakes, ponds, and flooded agricultural fields. In Delhi, the Yamuna floodplain, Okhla Bird Sanctuary, Najafgarh Jheel, and Sultanpur National Park are key wetland habitats.",
    range: "Delhi sits on the Central Asian Flyway — one of the world's great migratory routes. Resident species are joined by thousands of migratory waterbirds from Siberia, Central Asia, and Europe every winter (October–March).",
    diet: "Varies by species: herons and egrets hunt fish and frogs; ibises probe mud for invertebrates; storks forage in shallow water; pond herons wait motionless for prey to come within striking distance.",
    size: "Ranges from small (Pond Heron at 42–45 cm) to very large (Painted Stork at 93–102 cm, wingspan 150–160 cm). Includes diverse body plans — waders, swimmers, and divers.",
    behavior: "Many wetland species are colonial nesters, forming large breeding colonies (heronries) in trees near water. Delhi's Yamuna supports nesting colonies of Painted Storks, egrets, and cormorants. Winter migrants form large flocks at Okhla and Najafgarh.",
    threatsInDelhi: "Yamuna pollution is the #1 threat — industrial effluents, sewage, and agricultural runoff poison fish and contaminate wading areas. Habitat loss from wetland drainage and encroachment. Fishing line and net entanglement. Monsoon flooding displaces nests.",
    description: "Wildlife Rescue treats a growing number of wetland birds — from Painted Storks and Pond Herons to Red-naped Ibis and egrets. These birds depend on Delhi's rapidly shrinking wetlands, making each rescue both a wildlife emergency and an indicator of ecosystem health.",
    funFact: "Delhi's Okhla Bird Sanctuary, where the Yamuna meets the Agra Canal, hosts over 300 bird species — making it one of the richest birding sites in any major world capital. In winter, you can see Siberian migrants alongside Delhi's resident waterbirds.",
    image: "/species/cattle-egret.jpg",
    images: [
      { src: "/species/cattle-egret.jpg", alt: "Cattle Egret perched on examination table at Wildlife Rescue clinic" },
    ],
    videos: [
      { src: "/species/pond-herons.mp4", caption: "Pond Herons recovering at Wildlife Rescue — one of the many wetland species treated at the clinic" },
      { src: "/species/cattle-egret-video.mp4", caption: "A Cattle Egret in care at Wildlife Rescue — these common wetland birds are increasingly admitted with injuries from urban hazards and habitat loss along the Yamuna" },
    ],
  },
  {
    slug: "eagles",
    name: "Eagles",
    scientificName: "Various species",
    conservationStatus: "Mixed",
    iucnColor: "text-slate",
    percentage: "~0.8%",
    annualCases: "~30/year",
    category: "Raptor",
    habitat: "Open country, forest edges, and wetland margins. In Delhi, eagles are found near the Ridge forests, Yamuna floodplain, and on the outskirts where open agricultural land meets urban sprawl.",
    range: "Delhi hosts both resident and migratory eagle species. Steppe Eagles and Greater Spotted Eagles arrive as winter migrants from Central Asia. Tawny Eagles and Changeable Hawk-Eagles are year-round residents in the wider Delhi NCR region.",
    diet: "Powerful predators at the top of the food chain. Diet varies by species: Steppe Eagles take rodents and small mammals; Greater Spotted Eagles hunt waterbirds and fish; Changeable Hawk-Eagles take birds and small mammals in forest settings.",
    size: "Large to very large raptors. Steppe Eagle: 62–81 cm, wingspan 165–215 cm, weight 2–4.9 kg. Greater Spotted Eagle: 59–69 cm, wingspan 153–177 cm. These are among the largest birds that Wildlife Rescue treats.",
    behavior: "Eagles are apex predators with massive home ranges. Steppe Eagles soar on thermals over open country, scanning for prey. Greater Spotted Eagles prefer wetland edges. Both migratory species face hazards on their long journeys and arrive in Delhi from October onwards.",
    threatsInDelhi: "Electrocution from high-tension power lines — the #1 killer of large raptors. Vehicle collisions on highways. Secondary poisoning from rodenticides and pesticides. Habitat loss as open land is developed. For migratory species, hazards along the Central Asian Flyway (illegal hunting, habitat degradation).",
    description: "Eagles represent some of the most challenging and rewarding cases at Wildlife Rescue. Their large size demands specialized handling, and many species — like the Steppe Eagle (Endangered) and Greater Spotted Eagle (Vulnerable) — are of global conservation concern. Every eagle saved matters.",
    funFact: "The Steppe Eagle was recently uplisted to Endangered by IUCN due to dramatic population declines across its Central Asian breeding range. Delhi is one of the key wintering grounds for this species — making Wildlife Rescue's work directly relevant to the species' global survival.",
    image: "/species/cse-face.jpg",
    images: [
      { src: "/species/cse-face.jpg", alt: "Crested Serpent Eagle close-up showing distinctive yellow face and piercing eye" },
      { src: "/species/cse-treatment.jpg", alt: "Crested Serpent Eagle on examination table during treatment at Wildlife Rescue" },
    ],
  },
  {
    slug: "scops-owl",
    name: "Indian Scops Owl",
    scientificName: "Otus bakkamoena",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~0.5%",
    annualCases: "~20/year",
    category: "Raptor",
    habitat: "Wooded areas, gardens, orchards, groves of old trees, and leafy urban neighborhoods. In Delhi, found in the Ridge forests, Lodhi Gardens, and campuses with mature trees. Prefers dense foliage for daytime roosting.",
    range: "Resident across the Indian subcontinent, Sri Lanka, and into Southeast Asia. The Indian subspecies is non-migratory and found from the Himalayan foothills to the southern tip of India.",
    diet: "Primarily insects — beetles, moths, grasshoppers, and crickets. Also takes small rodents, lizards, and occasionally small birds. Hunts from a perch at night, swooping down on prey detected by sound and sight.",
    size: "Body length 20–25 cm, weight 100–170g. Small owl with prominent ear tufts (\"scops\" refers to these feathered tufts), large orange or brown eyes, and intricate bark-like camouflage plumage.",
    behavior: "Strictly nocturnal. Masters of camouflage — during the day they press against tree trunks with eyes shut and ear tufts raised, becoming virtually invisible against bark. Their soft, monotonous 'whuk... whuk... whuk' call is a characteristic sound of Delhi nights.",
    threatsInDelhi: "Loss of old trees with roosting and nesting cavities. Bright city lights disrupting nocturnal hunting. Window strikes during nighttime flights. Superstitious persecution — like other owls, sometimes considered bad omens. Vehicle collisions on lit roads at night.",
    description: "The Indian Scops Owl is one of Delhi's most secretive residents — present in far greater numbers than most people realize, but almost never seen thanks to their extraordinary camouflage. Wildlife Rescue treats approximately 20 per year, mostly birds that have collided with vehicles or windows at night.",
    funFact: "Indian Scops Owls are so perfectly camouflaged that they can roost on an open tree branch in broad daylight without being detected. They elongate their body, raise their ear tufts, and close their eyes to narrow slits — mimicking a broken branch stub with uncanny accuracy.",
    image: "/species/scops-owl-04.jpg",
    images: [
      { src: "/species/scops-owl-04.jpg", alt: "Indian Scops Owl front portrait showing intricate bark-like camouflage plumage and ear tufts" },
      { src: "/species/scops-owl-01.jpg", alt: "Indian Scops Owl with one eye half-open, showing distinctive ear tufts and grey-rufous plumage" },
      { src: "/species/scops-owl-02.jpg", alt: "Indian Scops Owl peering sideways with bright yellow eyes, showing camouflaged feather pattern" },
      { src: "/species/scops-owl.jpg", alt: "Indian Scops Owl with large orange-red eyes, perched in recovery enclosure at Wildlife Rescue" },
      { src: "/species/scops-owl-03.jpg", alt: "Indian Scops Owl resting with eyes closed, displaying cryptic bark-pattern plumage" },
      { src: "/species/scops-owl-clinic-01.jpg", alt: "Tiny Indian Scops Owl held in gloved hands during examination, showing huge dark eyes and raised ear tufts" },
      { src: "/species/scops-owl-clinic-02.jpg", alt: "Indian Scops Owl perched on handler's hand at Wildlife Rescue clinic, displaying full grey-white plumage and alert ear tufts" },
    ],
  },
  {
    slug: "steppe-eagle",
    name: "Steppe Eagle",
    scientificName: "Aquila nipalensis",
    conservationStatus: "Endangered",
    iucnColor: "text-danger",
    percentage: "~0.3%",
    annualCases: "~12/year",
    category: "Raptor",
    habitat: "Open grasslands, steppe, semi-desert, and agricultural plains. In Delhi, wintering birds are found near the Yamuna floodplain, landfill sites, and open agricultural land on the city's outskirts.",
    range: "Breeds across the vast steppes of Central Asia — from southern Russia and Kazakhstan through Mongolia to northern China. Migrates south in winter to the Indian subcontinent, the Middle East, and East Africa via the Central Asian Flyway.",
    diet: "Opportunistic predator and scavenger. On breeding grounds, feeds primarily on ground squirrels and other rodents. In India during winter, scavenges at carcass dumps, landfills, and slaughterhouse waste alongside Black Kites and vultures.",
    size: "Body length 62–81 cm, wingspan 165–215 cm, weight 2–4.9 kg. One of the largest raptors treated at Wildlife Rescue — a massive, powerful eagle with a distinctive wide yellow gape that extends behind the eye.",
    behavior: "Long-distance migrant — travels up to 10,000 km between breeding and wintering grounds. Soars on broad wings over open terrain. Less aggressive than some eagles; often feeds alongside vultures and kites at carcass sites. Arrives in Delhi from October and departs by March.",
    threatsInDelhi: "Electrocution from high-tension power lines is the leading cause of injury — their large wingspan bridges live wires. Secondary poisoning from diclofenac (the veterinary drug that devastated vulture populations) and rodenticides. Vehicle collisions on highways. Globally, habitat loss on Central Asian breeding grounds is driving population collapse.",
    description: "The Steppe Eagle is one of the most conservation-critical species that Wildlife Rescue treats. Uplisted to Endangered by IUCN in 2015 due to a 50–79% population decline over three generations, every individual matters. Delhi is a key wintering ground, and Wildlife Rescue's treatment of ~12 Steppe Eagles per year is a direct contribution to the survival of this magnificent species.",
    funFact: "Steppe Eagles fitted with GPS satellite trackers have been recorded crossing the Himalayas at altitudes above 4,000 meters during migration. One famous tracked eagle named 'Min' ran up a $2,600 roaming bill by sending SMS-based GPS data while flying through Iran — the researchers had to crowdfund to pay the phone bill.",
    image: "/species/steppe-eagle-01.jpg",
    images: [
      { src: "/species/steppe-eagle-01.jpg", alt: "Steppe Eagle face close-up showing powerful beak, distinctive yellow gape, and intense dark eyes" },
      { src: "/species/steppe-eagle-02.jpg", alt: "Steppe Eagle in recovery enclosure at Wildlife Rescue, showing full body with dark brown plumage and yellow talons" },
      { src: "/species/steppe-eagle-03.jpg", alt: "Steppe Eagle close-up during examination, displaying broad yellow gape and brown plumage" },
      { src: "/species/steppe-eagle-04.jpg", alt: "Steppe Eagle being assessed at Wildlife Rescue clinic, showing powerful yellow feet and dark feathering" },
    ],
  },
  {
    slug: "oriental-honey-buzzard",
    name: "Oriental Honey Buzzard",
    scientificName: "Pernis ptilorhynchus",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~0.3%",
    annualCases: "~10/year",
    category: "Raptor",
    habitat: "Dense deciduous and semi-evergreen forests, wooded hills, and forest edges. In Delhi, found in the Ridge forests (Sanjay Van, Northern Ridge) and wooded areas on the city's southern outskirts. Requires mature forest canopy for nesting.",
    range: "Widespread across South and Southeast Asia, from the Indian subcontinent to Japan and Indonesia. Northern populations are migratory; Indian birds are largely resident, with some altitudinal movement in the Himalayas.",
    diet: "Highly specialized — feeds primarily on the larvae, pupae, and combs of bees and wasps, raiding their nests in trees and underground. Also takes other insects, small reptiles, frogs, and occasionally fruit. Dense facial feathering protects against bee stings.",
    size: "Body length 52–68 cm, wingspan 120–150 cm, weight 750–1,500g. Medium-large raptor with a distinctive small head, long neck, and prominent erectile crest. Variable plumage — from pale to dark morphs.",
    behavior: "Patient hunter — will perch quietly near a bee or wasp nest, watching the flight paths of insects before approaching. Uses powerful feet to dig out underground nests. Soars on flat wings with a distinctive pigeon-like head profile. The erectile crest gives it a unique silhouette.",
    threatsInDelhi: "Habitat loss as Delhi's forested areas shrink. Electrocution from power lines at forest edges. Vehicle collisions on roads through wooded areas. Pesticide use reducing insect prey populations. Disturbance at nesting sites from construction and recreation.",
    description: "The Oriental Honey Buzzard is one of Delhi's most fascinating raptors — a specialized predator of bee and wasp nests that most Delhiites have never heard of. Despite looking like a typical raptor, their ecology is utterly unique. Wildlife Rescue treats approximately 10 per year, often birds that have collided with vehicles or power lines.",
    funFact: "Oriental Honey Buzzards have evolved dense, scale-like feathering on their faces to protect against bee and wasp stings while raiding nests. They also produce a chemical deterrent in their feathers that repels bees — one of the very few birds known to use chemical defense.",
    image: "/species/ohb-wingspan.jpg",
    imagePosition: "center top",
    images: [
      { src: "/species/ohb-wingspan.jpg", alt: "Oriental Honey Buzzard with wings fully spread during examination, showing broad wingspan and distinctive crest" },
      { src: "/species/ohb-wingspan-2.jpg", alt: "Oriental Honey Buzzard wings-spread view showing detailed feather pattern and barred tail" },
    ],
    video: { src: "/species/buzzard-baby.mp4", caption: "A juvenile Oriental Honey Buzzard in care at Wildlife Rescue — young buzzards require weeks of specialized feeding and rehabilitation before they can be released" },
  },
  {
    slug: "peregrine-falcon",
    name: "Peregrine Falcon",
    scientificName: "Falco peregrinus",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~0.2%",
    annualCases: "~8/year",
    category: "Raptor",
    habitat: "Cliffs, tall buildings, bridges, and open country. In Delhi, Peregrine Falcons have adapted to urban life, nesting on high-rise buildings, power plant chimneys, and large monuments — using them as artificial cliff faces.",
    range: "The most widespread raptor on Earth — found on every continent except Antarctica. The Indian subspecies (F. p. peregrinator, the Shaheen Falcon) is a resident breeder, while northern subspecies (F. p. calidus) migrate through Delhi in winter from Arctic and Central Asian breeding grounds.",
    diet: "Specialist bird hunter. Catches prey almost exclusively in flight — pigeons, doves, parakeets, and smaller birds. Hunts using spectacular high-speed stoops (dives), striking prey with clenched talons at tremendous speed.",
    size: "Body length 34–50 cm, wingspan 74–120 cm, weight 330–1,500g. Females significantly larger than males. Compact, powerful build with a distinctive dark 'moustache' stripe on the face, slate-grey upperparts, and barred underparts.",
    behavior: "The fastest animal on Earth — recorded at speeds exceeding 390 km/h (242 mph) in a hunting stoop. Territorial and aggressive, will defend nesting sites against much larger birds including eagles. In Delhi, hunts at dawn and dusk from high perches on buildings.",
    threatsInDelhi: "Building collisions during high-speed hunting pursuits through the urban landscape. Manja (glass-coated kite string) entanglement — particularly dangerous for a high-speed flier. Electrocution from power lines. Secondary poisoning from eating pigeons that have ingested rodenticides. Disturbance at urban nesting sites during construction.",
    description: "The Peregrine Falcon is the fastest animal on the planet and one of the most thrilling raptors that Wildlife Rescue treats. Though rare compared to Black Kites, each Peregrine case is remarkable — these are elite predators that have conquered Delhi's skyscraper canyons as their hunting grounds. Wildlife Rescue treats approximately 8 per year.",
    funFact: "During a hunting stoop, a Peregrine Falcon can exceed 390 km/h (242 mph) — faster than a Formula 1 car. To breathe at these speeds, they have special bony tubercles in their nostrils that redirect airflow, preventing their lungs from being damaged by the air pressure. Fighter jet engine intake designs have been inspired by this adaptation.",
    image: "/species/peregrine-falcon-hero.jpg",
    images: [
      { src: "/species/peregrine-falcon-hero.jpg", alt: "Peregrine Falcon portrait at Wildlife Rescue clinic showing dark moustachial stripe and bandaged wing" },
      { src: "/species/peregrine-falcon-01.jpg", alt: "Falcon held by handler during examination at Wildlife Rescue, showing brown plumage and alert expression" },
      { src: "/species/peregrine-falcon-02.jpg", alt: "Peregrine Falcon with body bandage during treatment, showing slate-grey and white plumage" },
      { src: "/species/peregrine-falcon-03.jpg", alt: "Peregrine Falcon in recovery with treatment bandage and case notes, perched at Wildlife Rescue clinic" },
    ],
  },
  {
    slug: "indian-grey-hornbill",
    name: "Indian Grey Hornbill",
    scientificName: "Ocyceros birostris",
    conservationStatus: "Least Concern",
    iucnColor: "text-success",
    percentage: "~0.4%",
    annualCases: "~15/year",
    category: "Cavity Nester",
    habitat: "Deciduous forests, orchards, and urban areas with large old trees. In Delhi, found in Ridge forests, old campuses (Delhi University, JNU), and areas with mature Ficus and Peepal trees.",
    range: "Endemic to the Indian subcontinent. Found across most of India except the northeast and extreme south.",
    diet: "Mainly fruit (figs are a favorite), supplemented with insects, lizards, and small vertebrates. Important seed disperser for many tree species.",
    size: "Body length 50–61 cm, weight 275–420g. Distinctive large curved bill with a casque (hornlike projection) on top.",
    behavior: "Famous for their extraordinary nesting behavior — the female seals herself inside a tree cavity with mud, leaving only a narrow slit for the male to pass food through. She remains sealed in for the entire incubation and chick-rearing period (~3 months).",
    threatsInDelhi: "Loss of old trees with suitable nesting cavities — the #1 threat. When old trees are cut, hornbills lose irreplaceable nesting sites. Window strikes. Competition for cavities with other species.",
    description: "The Indian Grey Hornbill is a barometer of urban tree health. Their presence indicates mature trees with cavities — a rapidly declining resource in Delhi's development boom. Wildlife Rescue treats about 15 per year.",
    funFact: "When the female hornbill seals herself inside the nesting cavity, she undergoes a complete feather molt — becoming temporarily flightless. She depends entirely on the male for food for up to 3 months. If the male dies, the female and chicks are trapped.",
  },
];

export function getSpeciesBySlug(slug: string): Species | undefined {
  return SPECIES_LIST.find((s) => s.slug === slug);
}
