#!/usr/bin/env node
/**
 * Website stats collector.
 *
 *   npm run stats        (or: node scripts/site-stats.mjs)
 *
 * Appends a dated snapshot to docs/site-stats-history.json and regenerates the
 * human-readable report docs/SITE-STATS.md. Re-running on the same day
 * overwrites that day's snapshot, so it's safe to run as often as you like.
 *
 * Tracks the metrics that actually grow over time (pages, code, media, commits,
 * content). Run it every so often (or on a schedule) to build a trend.
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "src");
const PUBLIC = path.join(ROOT, "public");
const DOCS = path.join(ROOT, "docs");

function walk(dir, fn) {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, fn);
    else fn(p);
  }
}
const read = (rel) => {
  try { return fs.readFileSync(path.join(ROOT, rel), "utf8"); } catch { return ""; }
};
const countMatches = (rel, re) => (read(rel).match(re) || []).length;
const MB = (b) => Math.round((b / 1048576) * 10) / 10;

// ── Source code ──────────────────────────────────────────────────────────────
let tsFiles = 0, linesOfCode = 0, routeTemplates = 0, apiEndpoints = 0, components = 0;
walk(SRC, (p) => {
  if (/\.(ts|tsx)$/.test(p)) {
    tsFiles++;
    linesOfCode += fs.readFileSync(p, "utf8").split("\n").length;
  }
  const b = path.basename(p);
  if (b === "page.tsx") routeTemplates++;
  if (b === "route.ts") apiEndpoints++;
});
walk(path.join(SRC, "components"), (p) => { if (p.endsWith(".tsx")) components++; });

// ── Public assets ────────────────────────────────────────────────────────────
const IMG = /\.(jpe?g|png|svg|webp|gif|ico)$/i, VID = /\.(mp4|mov)$/i, PDF = /\.pdf$/i;
let images = 0, imageBytes = 0, videos = 0, videoBytes = 0, pdfs = 0, publicBytes = 0;
walk(PUBLIC, (p) => {
  const sz = fs.statSync(p).size;
  publicBytes += sz;
  if (IMG.test(p)) { images++; imageBytes += sz; }
  else if (VID.test(p)) { videos++; videoBytes += sz; }
  else if (PDF.test(p)) pdfs++;
});

// ── Git ──────────────────────────────────────────────────────────────────────
const git = (c) => { try { return execSync(c, { cwd: ROOT }).toString().trim(); } catch { return ""; } };
const gitCommits = Number(git("git rev-list --count HEAD")) || 0;
const firstCommit = (git("git log --reverse --format=%ad --date=short").split("\n")[0]) || "";

// ── Content & data ───────────────────────────────────────────────────────────
const speciesProfiles = countMatches("src/lib/species-data.ts", /\n\s*slug:\s*"/g);
const conditions = countMatches("src/lib/conditions-data.ts", /\n\s*slug:\s*"/g);
const blogPostsStatic = countMatches("src/lib/blog-data.ts", /\n\s*slug:\s*"/g);
const intakeSpecies = countMatches("src/lib/intake-data.ts", /cases:\s*\d+,\s*iucn:/g);
const birdsMatch = read("src/lib/constants.ts").match(/number:\s*(\d+),\s*suffix:\s*"\+",\s*label:\s*"Birds Rescued/);
const birdsRescued = birdsMatch ? Number(birdsMatch[1]) : null;

// ── Snapshot ─────────────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10);
const snap = {
  date: today,
  birdsRescued,
  routeTemplates, apiEndpoints, components, tsFiles, linesOfCode,
  images, imageMB: MB(imageBytes), videos, videoMB: MB(videoBytes), pdfs, publicMB: MB(publicBytes),
  speciesProfiles, conditions, blogPostsStatic, intakeSpecies,
  gitCommits,
};

fs.mkdirSync(DOCS, { recursive: true });
const HIST = path.join(DOCS, "site-stats-history.json");
let history = [];
if (fs.existsSync(HIST)) { try { history = JSON.parse(fs.readFileSync(HIST, "utf8")); } catch { history = []; } }
history = history.filter((s) => s.date !== today);
history.push(snap);
history.sort((a, b) => a.date.localeCompare(b.date));
fs.writeFileSync(HIST, JSON.stringify(history, null, 2) + "\n");

// ── Report ───────────────────────────────────────────────────────────────────
const n = (v) => (typeof v === "number" ? v.toLocaleString("en-US") : v ?? "—");
const birds = birdsRescued ? `${n(birdsRescued)}+` : "—";
const rows = history
  .map((s) => `| ${s.date} | ${n(s.routeTemplates)} | ${n(s.components)} | ${n(s.linesOfCode)} | ${n(s.images)} | ${n(s.videos)} | ${n(s.publicMB)} | ${n(s.gitCommits)} | ${n(s.birdsRescued)} |`)
  .join("\n");

const md = `# Wildlife Rescue — Website Stats Report

_Auto-generated by \`scripts/site-stats.mjs\` — run \`npm run stats\` to refresh._
_Last updated: **${today}** · First commit: ${firstCommit}_

The website behind **${birds} bird rescues since 2010** — a Next.js 16 / React 19 /
Tailwind v4 app with an AI chatbot, live donations, and a Sanity CMS blog.

## At a glance — ${today}

### Under the hood
- **${n(routeTemplates)}** route templates (\`page.tsx\`) — the dynamic species / conditions / blog routes expand these to ~71 generated pages at build time
- **${n(apiEndpoints)}** API endpoints · **${n(components)}** reusable components
- **${n(tsFiles)}** TypeScript files · **${n(linesOfCode)}** lines of code
- **${n(gitCommits)}** git commits since ${firstCommit}

### Media library
- **${n(images)}** images (~${snap.imageMB} MB)
- **${n(videos)}** videos (~${snap.videoMB} MB)
- **${n(pdfs)}** PDF documents
- **${snap.publicMB} MB** total assets in \`/public\`

### Content & data
- **${n(speciesProfiles)}** species profiles · **${n(conditions)}** medical conditions · **${n(blogPostsStatic)}** static blog posts
- **${n(intakeSpecies)}** species in the intake analysis
- Context (reviewed periodically): 9 vulture species, 11 team members

## History

| Date | Routes | Components | Lines | Images | Videos | Public MB | Commits | Birds |
|------|-------:|-----------:|------:|-------:|-------:|----------:|--------:|------:|
${rows}

---
_Add a new snapshot anytime with \`npm run stats\`. Each run appends today's numbers; running again the same day overwrites that day's row. Raw data: \`docs/site-stats-history.json\`._
`;
fs.writeFileSync(path.join(DOCS, "SITE-STATS.md"), md);

console.log(`Snapshot saved for ${today} (${history.length} total in history):`);
console.log(snap);
